# CI script for Kora lib gfx on Travis
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -y binutils gcc make
  - sudo apt-get install -y libx11-dev

os:
  - linux
# - osx

arch:
  - amd64
  - arm64
env:
  - DISTO=kora
  - DISTO=x11
  - DISTO=bmp

compiler:
  - clang
  - gcc

install:
  - rm -rf build

script:
  - mkdir build
  - cd build
  - ../configure
  - make
  - make check

